# -*- coding: utf-8 -*-
"""Bingo tester

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxG_KqIgsCQ5aqHK7S_zO6yiIQeJJgR6
"""

import random

alphagrams = {
    "AAEINST": ["ENTASIA", "TAENIAS"],
    "ABEINST": ["BANTIES", "BASINET"],
    "ACEINST": ["ACETINS", "CINEAST"],
    "ADEINST": ["DESTAIN", "DETAINS", "INSTEAD", "NIDATES", "SAINTED", "SATINED", "STAINED"],
    "AEEINST": ["ETESIAN"],
    "AEFINST": ["FAINEST"],
    "AEGINST": ["EASTING", "EATINGS", "GENISTA", "INGATES", "INGESTA", "SEATING", "TAGINES", "TEASING"],
    "AEHINST": ["SHEITAN", "STHENIA"],
    "AEIINST": ["ISATINE"],
    "AEIJNST": ["TAJINES"],
    "AEIKNST": ["INTAKES"],
    "AEILNST": ["ELASTIN", "ENTAILS", "NAILSET", "SALIENT", "SALTINE", "SLAINTE", "TENAILS"],
    "AEIMNST": ["ETAMINS", "INMATES", "TAMEINS"],
    "AEINNST": ["INANEST", "STANINE"],
    "AEINOST": ["ATONIES"],
    "AEINPST": ["PANTIES", "PATINES", "SAPIENT", "SPINATE"],
    "AEINQST": [],
    "AEINRST": ["ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN"],
    "AEINSST": ["ENTASIS", "NASTIES", "SEITANS", "SESTINA", "TANSIES", "TISANES"],
    "AEINSTT": ["INSTATE", "SATINET"],
    "AEINSTU": ["AUNTIES", "SINUATE"],
    "AEINSTV": ["NAIVEST", "NATIVES", "VAINEST"],
    "AEINSTW": ["TAWNIES", "WANIEST"],
    "AEINSTX": ["ANTISEX", "SEXTAIN"],
    "AEINSTY": [],
    "AEINSTZ": ["ZANIEST", "ZEATINS"],
    "AAEINRT": [],
    "ABEINRT": [],
    "ACEINRT": ["CERATIN", "CERTAIN", "CREATIN", "TACRINE"],
    "ADEINRT": ["ANTIRED", "DETRAIN", "TRAINED"],
    "AEEINRT": ["ARENITE", "RETINAE", "TRAINEE"],
    "AEFINRT": ["FAINTER"],
    "AEGINRT": ["GRANITE", "GRATINE", "INGRATE", "TANGIER", "TEARING"],
    "AEHINRT": ["HAIRNET", "INEARTH", "THERIAN"],
    "AEIINRT": ["INERTIA"],
    "AEIJNRT": [],

    "AEIKNRT": ["KERATIN"],
    "AEILNRT": ["LATRINE", "RATLINE", "RELIANT", "RETINAL", "TRENAIL"],
    "AEIMNRT": ["MINARET", "RAIMENT"],
    "AEINNRT": ["ENTRAIN", "TRANNIE"],
    "AEINORT": [],
    "AEINPRT": ["INAPTER", "PAINTER", "PERTAIN", "REPAINT"],
    "AEINQRT": [],
    "AEINRRT": ["RETRAIN", "TERRAIN", "TRAINER"],
    "AEINRST": ["ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN"],
    "AEINRTT": ["INTREAT", "ITERANT", "NATTIER", "NITRATE", "TERTIAN"],
    "AEINRTU": ["RUINATE", "TAURINE", "URANITE", "URINATE"],
    "AEINRTV": [],
    "AEINRTW": ["TAWNIER", "TINWARE"],
    "AEINRTX": [],
    "AEINRTY": [],
    "AEINRTZ": [],
    "AAEIRST": ["ARISTAE", "ASTERIA", "ATRESIA"],
    "ABEIRST": ["BAITERS", "BARITES", "REBAITS", "TERBIAS"],
    "ACEIRST": ["ATRESIC", "CRISTAE", "RACIEST", "STEARIC"],
    "ADEIRST": ["ARIDEST", "ASTRIDE", "DIASTER", "DISRATE", "STAIDER", "TARDIES", "TIRADES"],
    "AEEIRST": ["AERIEST", "SERIATE"],
    "AEFIRST": ["FAIREST"],
    "AEGIRST": ["AIGRETS", "GAITERS", "SEAGIRT", "STAGIER", "TRIAGES"],
    "AEHIRST": ["HASTIER"],
    "AEIIRST": ["AIRIEST"],
    "AEIJRST": [],
    "AEIKRST": [],
    "AEILRST": ["REALIST", "RETAILS", "SALTIER", "SALTIRE", "SLATIER", "TAILERS"],
    "AEIMRST": ["IMARETS", "MAESTRI", "MISRATE", "SMARTIE"],
    "AEINRST": ["ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN"],
    "AEIORST": [],
    "AEIPRST": ["PARTIES", "PASTIER", "PIASTER", "PIASTRE", "PIRATES", "PRATIES", "TRAIPSE"],
    "AEIQRST": [],
    "AEIRRST": ["ARTSIER", "TARRIES", "TARSIER"],
    "AEIRSST": ["ARTSIES", "SATIRES"],
    "AEIRSTT": ["ARTIEST", "ARTISTE", "ATTIRES", "IRATEST", "RATITES", "STRIATE", "TASTIER"],
    "AEIRSTU": [],
    "AEIRSTV": ["RAVIEST", "VASTIER", "VERITAS"],
    "AEIRSTW": ["WAISTER", "WAITERS", "WARIEST", "WASTRIE"],
    "AEIRSTX": [],
    "AEIRSTY": [],
    "AEIRSTZ": [],
    "AAEINRS": ["ARSENIC", "CARNIES"],
    "ABEINRS": ["BASTION", "BRAINSE"],
    "ACEINRS": ["ARCSINE", "ARSENIC", "CARNIES"],
    "ADEINRS": ["RANDIES", "SANDIER", "SARDINE"],
    "AEEINRS": [],
    "AEFINRS": ["INFARES"],
    "AEGINRS": ["EARINGS", "ERASING", "GAINERS", "REAGINS", "REGAINS", "REGINAS", "SEARING", "SERINGA"],
    "AEHINRS": ["HERNIAS", "NEARISH"],
    "AEIINRS": ["SENARII"],
    "AEIJNRS": ["INJERAS"],
    "AEIKNRS": ["SNAKIER"],
    "AEILNRS": ["ALINERS", "NAILERS", "RENAILS"],
    "AEIMNRS": ["MARINES", "REMAINS", "SEMINAR"],
    "AEINNRS": ["INSANER", "INSNARE"],
    "AEINORS": ["ERASION"],
    "AEINPRS": ["PANIERS", "RAPINES"],
    "AEINQRS": [],
    "AEINRRS": ["SIERRAN"],
    "AEINRSS": ["ARSINES", "SARNIES"],
    "AEINRST": ["ANESTRI", "ANTSIER", "NASTIER", "RATINES", "RETAINS", "RETINAS", "RETSINA", "STAINER", "STEARIN"],
    "AEINRSU": [],
    "AEINRSV": ["RAVINES"],
    "AEINRSW": [],
    "AEINRSX": [],
    "AEINRSY": [],
    "AEINRSZ": []

}

def bingo_game():
    print("Welcome to the Bingo game!")

    stem_input = input("Enter a stem (retina/satire/tisane/arsine): ").strip().upper()

    if stem_input == "QUIT":
        print("Thanks for playing! Goodbye.")
        return

    stem_to_alphagram = {
        "RETINA": "AEINRT",
        "AIENRT": "AEINRT",
        "TISANE": "AEINST",
        "AEINST": "AEINST",
        "SATIRE": "AEIRST",
        "AEIRST": "AEIRST",
        "ARSINE":"AEINRS",
        "AEINRS":"AEINRS"
    }

    if stem_input == "RETINA" or stem_input == "AIENRT":
        selected_key = "AEINRT"

        quiz_alphagrams = [
            "AAEINRT", "ABEINRT", "ACEINRT", "ADEINRT", "AEEINRT", "AEFINRT", "AEGINRT",
            "AEHINRT", "AEIINRT", "AEIKNRT", "AEILNRT", "AEIMNRT", "AEINNRT", "AEINORT",
            "AEINPRT", "AEINRRT", "AEINRST", "AEINRTT", "AEINRTU", "AEINRTV", "AEINRTW"
        ]

        random.shuffle(quiz_alphagrams)

        for i in range(26):
            selected_quiz = quiz_alphagrams[i]
            print(f"\nYour alphagram is: {selected_quiz}")
            valid_bingos = alphagrams[selected_quiz]

            if not valid_bingos:
                print(f"No valid bingos available for the alphagram {selected_quiz}.")
                continue

            for attempt in range(2):
                bingo_input = input(f"Enter a bingo word you think can be formed (or type 'QUIT' to exit): ").strip().upper()
                if bingo_input == "QUIT":
                    print("Thanks for playing! Goodbye.")
                    return

                if bingo_input in valid_bingos:
                    print("Correct! You've found one of the valid bingos.\n")
                    break
                else:
                    if attempt == 1:
                        print(f"Incorrect. Here are all the possible valid bingos: {', '.join(valid_bingos)}\n")
                    else:
                        print("Incorrect. Try again!\n")

        bingo_game()

    elif stem_input == "TISANE" or stem_input == "AEINST":
        selected_key = "AEINST"

        quiz_alphagrams = [
            "AAEINST", "ABEINST", "ACEINST", "ADEINST", "AEEINST", "AEFINST", "AEGINST",
            "AEHINST", "AEIINST", "AEIJNST", "AEIKNST", "AEILNST", "AEIMNST", "AEINNST",
            "AEINOST", "AEINPST", "AEINQST", "AEINRST", "AEINSST", "AEINSTT", "AEINSTU",
            "AEINSTV", "AEINSTW", "AEINSTX", "AEINSTY", "AEINSTZ"
        ]

        random.shuffle(quiz_alphagrams)

        for i in range(26):
            selected_quiz = quiz_alphagrams[i]
            print(f"\nYour alphagram is: {selected_quiz}")
            valid_bingos = alphagrams[selected_quiz]

            if not valid_bingos:
                print(f"No valid bingos available for the alphagram {selected_quiz}.")
                continue

            for attempt in range(2):
                bingo_input = input(f"Enter a bingo word you think can be formed (or type 'QUIT' to exit): ").strip().upper()
                if bingo_input == "QUIT":
                    print("Thanks for playing! Goodbye.")
                    return

                if bingo_input in valid_bingos:
                    print("Correct! You've found one of the valid bingos.\n")
                    break
                else:
                    if attempt == 1:
                        print(f"Incorrect. Here are all the possible valid bingos: {', '.join(valid_bingos)}\n")
                    else:
                        print("Incorrect. Try again!\n")

        bingo_game()

    elif stem_input == "SATIRE" or stem_input == "AEIRST":
        selected_key = "AEIRST"

        quiz_alphagrams = [
            "AAEIRST", "ABEIRST", "ACEIRST", "ADEIRST", "AEEIRST", "AEFIRST", "AEGIRST",
            "AEHIRST", "AEIIRST", "AEIJRST", "AEIKRST", "AEILRST", "AEIMRST", "AEINRST",
            "AEIORST", "AEIPRST", "AEIQRST", "AEIRRST", "AEIRSST", "AEIRSTT", "AEIRSTU",
            "AEIRSTV", "AEIRSTW", "AEIRSTX", "AEIRSTY", "AEIRSTZ"
        ]

        random.shuffle(quiz_alphagrams)

        for i in range(26):
            selected_quiz = quiz_alphagrams[i]
            print(f"\nYour alphagram is: {selected_quiz}")
            valid_bingos = alphagrams[selected_quiz]

            if not valid_bingos:
                print(f"No valid bingos available for the alphagram {selected_quiz}.")
                continue

            for attempt in range(2):
                bingo_input = input(f"Enter a bingo word you think can be formed (or type 'QUIT' to exit): ").strip().upper()
                if bingo_input == "QUIT":
                    print("Thanks for playing! Goodbye.")
                    return

                if bingo_input in valid_bingos:
                    print("Correct! You've found one of the valid bingos.\n")
                    break
                else:
                    if attempt == 1:
                        print(f"Incorrect. Here are all the possible valid bingos: {', '.join(valid_bingos)}\n")
                    else:
                        print("Incorrect. Try again!\n")

        bingo_game()

    elif stem_input == "ARSINE" or stem_input == "AEINRS":
      selected_key = "AEINRS"

      quiz_alphagrams = [
          "AAEINRS", "ABEINRS", "ACEINRS", "ADEINRS", "AEEINRS", "AEFINRS", "AEGINRS",
          "AEHINRS", "AEIINRS", "AEIJNRS", "AEIKNRS", "AEILNRS", "AEIMNRS", "AEINNRS",
          "AEINORS", "AEINPRS", "AEINQRS", "AEINRRS", "AEINRSS", "AEINRST", "AEINRSU",
          "AEINRSV", "AEINRSW", "AEINRSX", "AEINRSY", "AEINRSZ"
      ]

      random.shuffle(quiz_alphagrams)

      for i in range(26):
          selected_quiz = quiz_alphagrams[i]
          print(f"\nYour alphagram is: {selected_quiz}")
          valid_bingos = alphagrams[selected_quiz]

          if not valid_bingos:
              print(f"No valid bingos available for the alphagram {selected_quiz}.")
              continue

          for attempt in range(26):
              bingo_input = input(f"Enter a bingo word you think can be formed (or type 'QUIT' to exit): ").strip().upper()
              if bingo_input == "QUIT":
                  print("Thanks for playing! Goodbye.")
                  return

              if bingo_input in valid_bingos:
                  print("Correct! You've found one of the valid bingos.\n")
                  break
              else:
                  if attempt == 1:
                      print(f"Incorrect. Here are all the possible valid bingos: {', '.join(valid_bingos)}\n")
                  else:
                      print("Incorrect. Try again!\n")

      bingo_game()


    else:
        print("Invalid input. Please enter a valid stem like 'retina', 'aienrt', 'tisane', or 'aeinst'.\n")
        bingo_game()

bingo_game()

